title: Nadie Lee el título wn
author: zurdo
email: sebafede2@gmail.com
description: este es mi Github page
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
